<?php

/**
 * Maps catalog icon ids to Tabler Icons SVG filenames (MIT license).
 * Run: npm run sync:map-icons
 *
 * @see public/icons/builtin/ATTRIBUTION.md
 */
return [
    'source' => 'tabler-icons',
    'source_version' => '3.31.0',
    'source_path' => 'node_modules/@tabler/icons/icons/outline',
    'filled_path' => 'node_modules/@tabler/icons/icons/filled',
    'render' => [
        'canvas' => 64,
        'icon_scale' => 2,
        'padding' => 8,
        'soft_background' => true,
        'prefer_filled' => true,
    ],

    /** Default vivid colors per picker category */
    'category_colors' => [
        'vehicles' => '#2563eb',
        'aircraft' => '#6366f1',
        'marine' => '#0891b2',
        'assets' => '#d97706',
        'animals' => '#b45309',
        'people' => '#7c3aed',
    ],

    /**
     * Per-icon overrides (hex). Falls back to category_colors.
     *
     * @var array<string, string>
     */
    'icon_colors' => [
        'car' => '#2563eb',
        'suv' => '#1d4ed8',
        'pickup_truck' => '#ea580c',
        'van' => '#3b82f6',
        'mini_van' => '#60a5fa',
        'cargo_van' => '#0284c7',
        'taxi' => '#fbbf24',
        'bus' => '#f59e0b',
        'school_bus' => '#f59e0b',
        'truck' => '#c2410c',
        'semi_truck' => '#9a3412',
        'trailer_truck' => '#7c2d12',
        'flatbed_trailer' => '#b45309',
        'container_truck' => '#0369a1',
        'tanker_truck' => '#64748b',
        'dump_truck' => '#ca8a04',
        'refrigerated_truck' => '#38bdf8',
        'cement_mixer' => '#94a3b8',
        'garbage_truck' => '#16a34a',
        'tow_truck' => '#f97316',
        'forklift' => '#eab308',
        'excavator' => '#ca8a04',
        'bulldozer' => '#eab308',
        'crane' => '#ea580c',
        'loader' => '#d97706',
        'ambulance' => '#ef4444',
        'police_car' => '#1e40af',
        'fire_truck' => '#dc2626',
        'atv' => '#166534',
        'bicycle' => '#22c55e',
        'motorcycle' => '#475569',
        'scooter' => '#0ea5e9',
        'tractor' => '#16a34a',
        'helicopter' => '#6366f1',
        'airplane' => '#818cf8',
        'private_jet' => '#4f46e5',
        'hot_air_balloon' => '#ef4444',
        'drone' => '#334155',
        'sail_boat' => '#06b6d4',
        'speed_boat' => '#0ea5e9',
        'yacht' => '#0284c7',
        'cargo_ship' => '#0369a1',
        'fishing_boat' => '#14b8a6',
        'ferry' => '#0891b2',
        'container_red' => '#ef4444',
        'container_blue' => '#3b82f6',
        'container_green' => '#22c55e',
        'container_yellow' => '#eab308',
        'package' => '#d97706',
        'pallet' => '#a16207',
        'fuel_tank' => '#64748b',
        'generator' => '#475569',
        'gps_device' => '#0f172a',
        'radio_device' => '#334155',
        'dog' => '#b45309',
        'cat' => '#78716c',
        'horse' => '#92400e',
        'camel' => '#a16207',
        'cow' => '#57534e',
        'turtle' => '#16a34a',
        'zebra' => '#292524',
        'sheep' => '#a8a29e',
        'goat' => '#78716c',
        'person' => '#2563eb',
        'walking_person' => '#3b82f6',
        'security_guard' => '#1e3a8a',
        'worker' => '#ea580c',
    ],

    'category_folders' => [
        'vehicles' => 'Vehicles',
        'aircraft' => 'Aircraft',
        'marine' => 'Marine',
        'assets' => 'Assets',
        'animals' => 'Animals',
        'people' => 'People',
    ],

    /**
     * icon id => Tabler outline icon filename (without .svg)
     *
     * @var array<string, string>
     */
    'tabler' => [
        'car' => 'car',
        'bicycle' => 'bike',
        'motorcycle' => 'motorbike',
        'scooter' => 'scooter',
        'tractor' => 'tractor',
        'suv' => 'car-suv',
        'pickup_truck' => 'truck',
        'van' => 'rv-truck',
        'mini_van' => 'car',
        'cargo_van' => 'truck-delivery',
        'taxi' => 'car',
        'bus' => 'bus',
        'school_bus' => 'school',
        'truck' => 'truck',
        'semi_truck' => 'truck-loading',
        'trailer_truck' => 'truck-loading',
        'flatbed_trailer' => 'truck-return',
        'container_truck' => 'truck-loading',
        'tanker_truck' => 'truck',
        'dump_truck' => 'bulldozer',
        'refrigerated_truck' => 'truck-delivery',
        'cement_mixer' => 'crane',
        'garbage_truck' => 'truck-off',
        'tow_truck' => 'crane',
        'forklift' => 'forklift',
        'excavator' => 'bulldozer',
        'bulldozer' => 'bulldozer',
        'crane' => 'crane',
        'loader' => 'bulldozer',
        'ambulance' => 'ambulance',
        'police_car' => 'shield-check',
        'fire_truck' => 'firetruck',
        'atv' => 'car-4wd',
        'helicopter' => 'helicopter',
        'airplane' => 'plane-inflight',
        'hot_air_balloon' => 'balloon',
        'drone' => 'drone',
        'private_jet' => 'plane-departure',
        'sail_boat' => 'sailboat',
        'speed_boat' => 'speedboat',
        'yacht' => 'sailboat-2',
        'cargo_ship' => 'ship',
        'fishing_boat' => 'sailboat-off',
        'ferry' => 'ferry',
        'container_red' => 'container',
        'container_blue' => 'container',
        'container_green' => 'container',
        'container_yellow' => 'container',
        'package' => 'package',
        'pallet' => 'packages',
        'fuel_tank' => 'gas-station',
        'generator' => 'engine',
        'gps_device' => 'device-mobile',
        'radio_device' => 'radio',
        'dog' => 'dog',
        'cat' => 'cat',
        'horse' => 'horse',
        'camel' => 'horse',
        'cow' => 'pig',
        'turtle' => 'fish',
        'zebra' => 'horse',
        'sheep' => 'dog',
        'goat' => 'horse',
        'person' => 'user',
        'walking_person' => 'walk',
        'security_guard' => 'shield-check',
        'worker' => 'tool',
    ],
];
