<?php

/**
 * Built-in vehicle icon catalog for map marker customization.
 * UI categories match the picker: vehicles, aircraft, marine, assets, animals, people.
 * Each icon maps to a top-down SVG under public/icons/builtin/{Category}/{id}.svg
 * (generated by: npm run generate:map-icons).
 */
return [
        'categories' => [
        'vehicles' => ['label_key' => 'icon_cat_vehicles', 'order' => 10, 'emoji' => ''],
        'aircraft' => ['label_key' => 'icon_cat_aircraft', 'order' => 20, 'emoji' => ''],
        'marine' => ['label_key' => 'icon_cat_marine', 'order' => 30, 'emoji' => ''],
        'assets' => ['label_key' => 'icon_cat_assets', 'order' => 40, 'emoji' => ''],
        'animals' => ['label_key' => 'icon_cat_animals', 'order' => 50, 'emoji' => ''],
        'people' => ['label_key' => 'icon_cat_people', 'order' => 60, 'emoji' => ''],
    ],

    /** @deprecated Use category — kept for backward compat with older group labels */
    'legacy_group_map' => [
        'vehicles' => 'road',
        'aircraft' => 'special',
        'marine' => 'special',
        'assets' => 'other',
        'animals' => 'other',
        'people' => 'other',
        // legacy category ids still contiguous in aliases
        'cars' => 'road',
        'trucks' => 'road',
        'buses' => 'road',
        'motorcycles' => 'road',
        'heavy_equipment' => 'special',
        'emergency' => 'emergency',
        'utility' => 'road',
        'aviation' => 'special',
        'agriculture' => 'special',
        'railway' => 'special',
        'special' => 'other',
        'generic' => 'other',
    ],

    'aliases' => [
        'police' => 'police_car',
        'pickup' => 'pickup_truck',
        'fire_truck' => 'fire_truck',
        'other' => 'car',
        'default_vehicle' => 'car',
        'sedan' => 'car',
        'boat' => 'sail_boat',
        'shipping_container' => 'container_red',
        'pet' => 'dog',
        'livestock' => 'cow',
        'gps_tracker' => 'gps_device',
        'portable_asset' => 'package',
        'machinery' => 'generator',
    ],

    'icons' => [
        // ── Vehicles ──────────────────────────────────────────────
        'car' => ['category' => 'vehicles', 'shape' => 'car', 'label' => 'Sedan', 'tags' => ['car', 'auto', 'sedan']],
        'bicycle' => ['category' => 'vehicles', 'shape' => 'bicycle', 'label' => 'Bicycle', 'tags' => ['bicycle', 'bike']],
        'motorcycle' => ['category' => 'vehicles', 'shape' => 'motorcycle', 'label' => 'Motorcycle', 'tags' => ['motorcycle', 'bike']],
        'scooter' => ['category' => 'vehicles', 'shape' => 'scooter', 'label' => 'Scooter', 'tags' => ['scooter']],
        'tractor' => ['category' => 'vehicles', 'shape' => 'tractor', 'label' => 'Tractor', 'tags' => ['tractor', 'farm']],
        'suv' => ['category' => 'vehicles', 'shape' => 'suv', 'label' => 'SUV', 'tags' => ['suv', '4x4']],
        'pickup_truck' => ['category' => 'vehicles', 'shape' => 'pickup', 'label' => 'Pickup', 'tags' => ['pickup', 'truck']],
        'van' => ['category' => 'vehicles', 'shape' => 'van', 'label' => 'Van', 'tags' => ['van']],
        'mini_van' => ['category' => 'vehicles', 'shape' => 'mini_van', 'label' => 'Mini Van', 'tags' => ['minivan', 'van']],
        'cargo_van' => ['category' => 'vehicles', 'shape' => 'cargo_van', 'label' => 'Cargo Van', 'tags' => ['cargo', 'van']],
        'taxi' => ['category' => 'vehicles', 'shape' => 'taxi', 'label' => 'Taxi', 'tags' => ['taxi', 'cab']],
        'bus' => ['category' => 'vehicles', 'shape' => 'bus', 'label' => 'Bus', 'tags' => ['bus', 'transit']],
        'school_bus' => ['category' => 'vehicles', 'shape' => 'school_bus', 'label' => 'School Bus', 'tags' => ['school', 'bus']],
        'truck' => ['category' => 'vehicles', 'shape' => 'truck', 'label' => 'Truck', 'tags' => ['truck', 'lorry']],
        'semi_truck' => ['category' => 'vehicles', 'shape' => 'semi', 'label' => 'Semi Truck', 'tags' => ['semi', 'truck']],
        'trailer_truck' => ['category' => 'vehicles', 'shape' => 'trailer_truck', 'label' => 'Trailer Truck', 'tags' => ['trailer', 'truck']],
        'flatbed_trailer' => ['category' => 'vehicles', 'shape' => 'flatbed', 'label' => 'Flatbed Trailer', 'tags' => ['flatbed', 'trailer']],
        'container_truck' => ['category' => 'vehicles', 'shape' => 'container_truck', 'label' => 'Container Truck', 'tags' => ['container', 'truck']],
        'tanker_truck' => ['category' => 'vehicles', 'shape' => 'tanker', 'label' => 'Tanker Truck', 'tags' => ['tanker', 'fuel']],
        'dump_truck' => ['category' => 'vehicles', 'shape' => 'dump_truck', 'label' => 'Dump Truck', 'tags' => ['dump', 'truck']],
        'refrigerated_truck' => ['category' => 'vehicles', 'shape' => 'refrigerated_truck', 'label' => 'Refrigerated Truck', 'tags' => ['reefer', 'cold', 'truck']],
        'cement_mixer' => ['category' => 'vehicles', 'shape' => 'cement_mixer', 'label' => 'Cement Mixer', 'tags' => ['cement', 'mixer']],
        'garbage_truck' => ['category' => 'vehicles', 'shape' => 'garbage_truck', 'label' => 'Garbage Truck', 'tags' => ['garbage', 'waste']],
        'tow_truck' => ['category' => 'vehicles', 'shape' => 'tow_truck', 'label' => 'Tow Truck', 'tags' => ['tow', 'recovery']],
        'forklift' => ['category' => 'vehicles', 'shape' => 'forklift', 'label' => 'Forklift', 'tags' => ['forklift', 'warehouse']],
        'excavator' => ['category' => 'vehicles', 'shape' => 'excavator', 'label' => 'Excavator', 'tags' => ['excavator', 'construction']],
        'bulldozer' => ['category' => 'vehicles', 'shape' => 'bulldozer', 'label' => 'Bulldozer', 'tags' => ['bulldozer', 'construction']],
        'crane' => ['category' => 'vehicles', 'shape' => 'crane', 'label' => 'Crane', 'tags' => ['crane']],
        'loader' => ['category' => 'vehicles', 'shape' => 'loader', 'label' => 'Loader', 'tags' => ['loader', 'construction']],
        'ambulance' => ['category' => 'vehicles', 'shape' => 'ambulance', 'label' => 'Ambulance', 'tags' => ['ambulance', 'emergency']],
        'police_car' => ['category' => 'vehicles', 'shape' => 'police', 'label' => 'Police Car', 'tags' => ['police', 'emergency']],
        'fire_truck' => ['category' => 'vehicles', 'shape' => 'fire_truck', 'label' => 'Fire Truck', 'tags' => ['fire', 'emergency']],
        'atv' => ['category' => 'vehicles', 'shape' => 'atv', 'label' => 'ATV', 'tags' => ['atv', 'quad']],

        // ── Aircraft ──────────────────────────────────────────────
        'helicopter' => ['category' => 'aircraft', 'shape' => 'helicopter', 'label' => 'Helicopter', 'tags' => ['helicopter', 'aircraft']],
        'airplane' => ['category' => 'aircraft', 'shape' => 'airplane', 'label' => 'Airplane', 'tags' => ['airplane', 'aircraft']],
        'hot_air_balloon' => ['category' => 'aircraft', 'shape' => 'hot_air_balloon', 'label' => 'Hot Air Balloon', 'tags' => ['balloon', 'aircraft']],
        'drone' => ['category' => 'aircraft', 'shape' => 'drone', 'label' => 'Drone', 'tags' => ['drone', 'uav']],
        'private_jet' => ['category' => 'aircraft', 'shape' => 'private_jet', 'label' => 'Private Jet', 'tags' => ['jet', 'aircraft']],

        // ── Marine ────────────────────────────────────────────────
        'sail_boat' => ['category' => 'marine', 'shape' => 'sail_boat', 'label' => 'Sail Boat', 'tags' => ['sail', 'boat', 'marine']],
        'speed_boat' => ['category' => 'marine', 'shape' => 'speed_boat', 'label' => 'Speed Boat', 'tags' => ['speedboat', 'marine']],
        'yacht' => ['category' => 'marine', 'shape' => 'yacht', 'label' => 'Yacht', 'tags' => ['yacht', 'marine']],
        'cargo_ship' => ['category' => 'marine', 'shape' => 'cargo_ship', 'label' => 'Cargo Ship', 'tags' => ['ship', 'cargo']],
        'fishing_boat' => ['category' => 'marine', 'shape' => 'fishing_boat', 'label' => 'Fishing Boat', 'tags' => ['fishing', 'boat']],
        'ferry' => ['category' => 'marine', 'shape' => 'ferry', 'label' => 'Ferry', 'tags' => ['ferry', 'boat']],

        // ── Assets ────────────────────────────────────────────────
        'container_red' => ['category' => 'assets', 'shape' => 'container_red', 'label' => 'Red Container', 'tags' => ['container', 'red']],
        'container_blue' => ['category' => 'assets', 'shape' => 'container_blue', 'label' => 'Blue Container', 'tags' => ['container', 'blue']],
        'container_green' => ['category' => 'assets', 'shape' => 'container_green', 'label' => 'Green Container', 'tags' => ['container', 'green']],
        'container_yellow' => ['category' => 'assets', 'shape' => 'container_yellow', 'label' => 'Yellow Container', 'tags' => ['container', 'yellow']],
        'package' => ['category' => 'assets', 'shape' => 'package', 'label' => 'Package', 'tags' => ['package', 'box', 'parcel']],
        'pallet' => ['category' => 'assets', 'shape' => 'pallet', 'label' => 'Pallet', 'tags' => ['pallet', 'cargo']],
        'fuel_tank' => ['category' => 'assets', 'shape' => 'fuel_tank', 'label' => 'Fuel Tank', 'tags' => ['fuel', 'tank']],
        'generator' => ['category' => 'assets', 'shape' => 'generator', 'label' => 'Generator', 'tags' => ['generator']],
        'gps_device' => ['category' => 'assets', 'shape' => 'gps_device', 'label' => 'GPS Device', 'tags' => ['gps', 'tracker', 'device']],
        'radio_device' => ['category' => 'assets', 'shape' => 'radio_device', 'label' => 'Radio Device', 'tags' => ['radio', 'device']],

        // ── Animals ───────────────────────────────────────────────
        'dog' => ['category' => 'animals', 'shape' => 'dog', 'label' => 'Dog', 'tags' => ['dog', 'pet']],
        'cat' => ['category' => 'animals', 'shape' => 'cat', 'label' => 'Cat', 'tags' => ['cat', 'pet']],
        'horse' => ['category' => 'animals', 'shape' => 'horse', 'label' => 'Horse', 'tags' => ['horse']],
        'camel' => ['category' => 'animals', 'shape' => 'camel', 'label' => 'Camel', 'tags' => ['camel']],
        'cow' => ['category' => 'animals', 'shape' => 'cow', 'label' => 'Cow', 'tags' => ['cow', 'cattle']],
        'turtle' => ['category' => 'animals', 'shape' => 'turtle', 'label' => 'Turtle', 'tags' => ['turtle']],
        'zebra' => ['category' => 'animals', 'shape' => 'zebra', 'label' => 'Zebra', 'tags' => ['zebra']],
        'sheep' => ['category' => 'animals', 'shape' => 'sheep', 'label' => 'Sheep', 'tags' => ['sheep']],
        'goat' => ['category' => 'animals', 'shape' => 'goat', 'label' => 'Goat', 'tags' => ['goat']],

        // ── People ────────────────────────────────────────────────
        'person' => ['category' => 'people', 'shape' => 'person', 'label' => 'Person', 'tags' => ['person', 'human']],
        'walking_person' => ['category' => 'people', 'shape' => 'walking_person', 'label' => 'Walking Person', 'tags' => ['walking', 'person']],
        'security_guard' => ['category' => 'people', 'shape' => 'security_guard', 'label' => 'Security Guard', 'tags' => ['security', 'guard']],
        'worker' => ['category' => 'people', 'shape' => 'worker', 'label' => 'Worker', 'tags' => ['worker', 'labor']],
    ],
];
